In [2]:
'''
Short code to combine the locations with the results. This is sometimes called a "join," where you 
combine two dataframes based on a "key" (like camera ID). 

In this case we have two dataframes, 1) the dataframe of your model outputs which has camera ID and filename 
as two separate columns and 2) the locations metadata that Morgan provided. 

We will conduct a "join" to combine the two dataframes based on the camera ID. Think about it this way: the code
will walk through our dataframe of model outputs and for each camera ID, it will look up the location for that 
respective camera ID in Morgan's table and add it as a column. 

Note: the reason why the locations weren't originally written into the script is because the locations are usually 
provided as a separate file anyways.

To run: 

from directory 
python add_location_data.py

'''

'\nShort code to combine the locations with the results. This is sometimes called a "join," where you \ncombine two dataframes based on a "key" (like camera ID). \n\nIn this case we have two dataframes, 1) the dataframe of your model outputs which has camera ID and filename \nas two separate columns and 2) the locations metadata that Morgan provided. \n\nWe will conduct a "join" to combine the two dataframes based on the camera ID. Think about it this way: the code\nwill walk through our dataframe of model outputs and for each camera ID, it will look up the location for that \nrespective camera ID in Morgan\'s table and add it as a column. \n\nNote: the reason why the locations weren\'t originally written into the script is because the locations are usually \nprovided as a separate file anyways.\n\nTo run: \n\nfrom directory \npython add_location_data.py\n\n'

In [ ]:
# library to do the join
import pandas as pd
from pathlib import Path

In [5]:
##################### UPDATE WITH OWN PATH HERE ###############
## this is now Payton's csv: 
data = pd.read_csv(Path("/Users/cmbreen/Documents/FDLTCC/payton_fix/results.csv"))
data.head()

,Unnamed: 0,camera_id,filename,x1_pred,y1_pred,x2_pred,y2_pred,total_length_pixel,snow_depth
0,0,ET,ET_2025_WSCT1522.JPG,2799.6306,760.36470,2729.1086,2522.2430,1763.288940,0
1,1,ET,ET_2025_WSCT1523.JPG,2910.8992,786.06630,2879.2834,2537.7650,1751.983887,0
2,2,ET,ET_2025_WSCT1524.JPG,2795.4430,616.80820,2636.1940,2462.1226,1852.173096,0
3,3,ET,ET_2025_WSCT1525.JPG,2876.1710,651.99310,2696.8716,2523.2559,1879.833008,0
4,4,ET,ET_2025_WSCT1526.JPG,2761.6519,796.39935,2734.2412,2582.6206,1786.431519,0

In [ ]:
## all camera id's using unique function from pandas
print(pd.unique(data['camera_id']))

['ET' 'FT' 'GT' 'SL' 'ST' 'TL' 'TW']

In [11]:
################## UPDATE WITH OWN PATH HERE #################
locations = pd.read_csv(Path("/Users/cmbreen/Documents/FDLTCC/1854TA_SnowStation_Locations.csv"))
#print(locations.head())
print(pd.unique(locations['Site ID']))

['GP3' 'GP2' 'GP1' 'SL' 'TL' 'FT' 'SG3' 'ST' 'FF' 'TW' 'ET' 'SW' 'GT']

In [ ]:
merged = pd.merge(data, locations, left_on = 'camera_id', right_on = "Site ID")

In [17]:
merged

,Unnamed: 0,camera_id,filename,x1_pred,y1_pred,x2_pred,y2_pred,total_length_pixel,snow_depth,Site ID_x,Site Name,Site ID_y,Lat,Long
0,0,ET,ET_2025_WSCT1522.JPG,2799.6306,760.36470,2729.1086,2522.2430,1763.288940,0,,Echo Trail,ET,48.16497,-92.50789
1,1,ET,ET_2025_WSCT1523.JPG,2910.8992,786.06630,2879.2834,2537.7650,1751.983887,0,,Echo Trail,ET,48.16497,-92.50789
2,2,ET,ET_2025_WSCT1524.JPG,2795.4430,616.80820,2636.1940,2462.1226,1852.173096,0,,Echo Trail,ET,48.16497,-92.50789
3,3,ET,ET_2025_WSCT1525.JPG,2876.1710,651.99310,2696.8716,2523.2559,1879.833008,0,,Echo Trail,ET,48.16497,-92.50789
4,4,ET,ET_2025_WSCT1526.JPG,2761.6519,796.39935,2734.2412,2582.6206,1786.431519,0,,Echo Trail,ET,48.16497,-92.50789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3440,3440,TW,TW_2025_WSCT2076.JPG,2997.2354,460.07462,2666.4895,2644.3103,2209.135010,0,,Tower,TW,47.79960,-92.28623
3441,3441,TW,TW_2025_WSCT2077.JPG,2957.4941,480.55768,2720.3313,2580.5627,2113.354736,0,,Tower,TW,47.79960,-92.28623
3442,3442,TW,TW_2025_WSCT2078.JPG,2976.7837,445.12082,2869.3416,2522.7234,2080.378906,0,,Tower,TW,47.79960,-92.28623
3443,3443,TW,TW_2025_WSCT2079.JPG,2967.3232,442.68628,2805.4204,2570.9133,2134.376465,0,,Tower,TW,47.79960,-92.28623
3444,3444,TW,TW_2025_WSCT2080.JPG,3015.4229,525.22480,2770.4148,2635.3513,2124.302979,0,,Tower,TW,47.79960,-92.28623

In [18]:
merged.to_csv('/Users/cmbreen/Documents/FDLTCC/payton_fix/results_location_v2.csv')